### ISSUE TITLE
Add repository field to package JSON

### ISSUE THREAD

**Issue by T1m1** [flatiron/cradle#283]
Hello,

it is possible to add the repository field to the package json? I get a warning during compiling.

"repository": {
    "type": "git",
    "url": "git://github.com/flatiron/cradle.git"
  },

**Comment by panuhorsmalahti** [comment]
Sure, PR's are welcome :)

**Comment by panuhorsmalahti** [comment]
Accorind go the documentation ``"repository": "flatiron/cradle"`` is sufficient.

**Comment by panuhorsmalahti** [comment]
Fixed:
https://github.com/flatiron/cradle/commit/632a9fededb774ba5ecb94d3a268280f1bb62a88

**Comment by T1m1** [comment]
Thank you for the fast handling :+1:
