### ISSUE TITLE
querystring.escape causing problems?

### ISSUE THREAD

**Issue by muzfuz** [flatiron/cradle#295]
```
cradle 0.6.9
node 4.2.1
```

`querystring.escape` is giving me 'undefined' errors in the `db.view()` function.  

Replacing it something like `querystring.stringify` or `encodeURIComponent` seems to fix the issue.  Not really sure what's up with that, so I thought I'd mention it here if anyone else has encountered similar problems.

**Comment by OliverOliverOliverAnders** [comment]
Hi,

I face the same issue
Oliver
